project:
  type: website
  output-dir: docs

website:
  title: "HenriqueSchall"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Portfolio.qmd
      - Substack.qmd
      - CV.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true



